Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('category_list', views.category_list),
    path('category_detail', views.category_detail),
    path('product_list', views.product_list),
    path('product_detail/<int:id>', views.product_detail),
    path('wishlist', views.wishlist),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('carts', views.carts, name='carts'),
    path('cart_detail', views.cart_detail, name='cart_detail'),
    path('cart/detail/delete/', views.cart_detail_delete, name='cart_detail_delete'),
    path('cart_sale/<int:id>', views.cart_sale, name='cart_sale'),
    path('cart_create/<int:id>/', views.cart_create, name='cart_create'),
    
    path('wishlist', views.wishlist, name='wishlist'),
    path('add_wish/<int:id>', views.add_wish, name='add_wish'),
    path('del_wish/<int:id>', views.del_wish, name='del_wish'),
]

main/models.py
from time import timezone
from typing import Iterable
from django.db import models
from django.contrib.auth.models import User
from functools import reduce
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from unidecode import unidecode


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(Category, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    quantity = models.IntegerField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    currency = models.SmallIntegerField(
        choices=(
            (1,'Dollar'), 
            (2, 'So`m')
            )
    ) 
    discount_price = models.DecimalField(
        decimal_places=2, 
        max_digits=10, 
        blank=True, 
        null=True
        )
    baner_image = models.ImageField(upload_to='baner/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(Product, self).save(*args, **kwargs)


    @property
    def review(self):
        reviews = ProductReview.objects.filter(product_id=self.id)
        result = reduce(lambda result, x: result +x, reviews, 0)
        try:
            result = result / reviews.count()
        except ZeroDivisionError:
            result = 0
        return result
    
    @property 
    def is_discount(self):
        if self.discount_price is None:
            return 0
        return self.discount_price > 0
    
    @property 
    def is_active(self):
        return self.quantity > 0


class EnterProduct(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity_enter_notation = models.SmallIntegerField(
        choices=(
            (0,'Ayrish'), 
            (1, 'Qo`shish')
            ), null=True, blank=True
    ) 
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(EnterProduct, self).save(*args, **kwargs)


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(ProductImage, self).save(*args, **kwargs)


class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(WishList, self).save(*args, **kwargs)

def check_duplicate_wishlist(sender, instance, **kwargs):
    if WishList.objects.filter(user=instance.user, product=instance.product).exists():
        raise ValidationError("This product is already in the wishlist.")

models.signals.pre_save.connect(check_duplicate_wishlist, sender=WishList)


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    mark = models.SmallIntegerField()
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(ProductReview, self).save(*args, **kwargs)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(Cart, self).save(*args, **kwargs)

    @property
    def quantity(self):
        quantity = 0
        products = CartProduct.objects.filter(product_id = self.id)
        for i in products:
            quantity +=i.quantity
        return quantity

    @property
    def total_price(self):
        result = 0
        for i in CartProduct.objects.filter(card_id=self.id):
            result +=(i.product.price)*i.quantity
        return result


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(CartProduct, self).save(*args, **kwargs)
    
    @property
    def total_price(self):
        if self.product.is_discount:
            result = self.product.discount_price * self.quantity
        else:
            result = self.product.price * self.quantity
        return result

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . import models
from django.db.models import Q


def index(request):
    q = request.GET.get('q')
    if q:
        products = models.Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q))
    else: 
        products = models.Product.objects.filter(quantity__gt=0)
    categorys = models.Category.objects.all()
    category_id = request.GET.get('category_id')
    if category_id:
        products.filter(category_id=category_id)
        
    wishs = models.WishList.objects.all()
    wish_ids = []
    for obj in wishs:
        product = models.Product.objects.get(id=obj.product.id)
        wish_ids.append(product.id)
    context = {
        'products':products,
        'categorys':categorys,
        'wish_ids':wish_ids
    }
    return render(request, 'index.html', context)




def product_detail(request, id):
    product = models.Product.objects.get(id=id)
    categorys = models.Category.objects.all()
    recomendation = models.Product.objects.filter(
        category_id=product.category.id).exclude(id=product.id)[:3]
    images = models.ProductImage.objects.filter(product_id=product.id)
    try:
        wish = models.WishList.objects.get(user=request.user, product=product)
        res = wish.id
    except:
        res = 0

    context = {
        'product':product,
        'categorys':categorys,
        'recomendation':recomendation,
        'images':images,
        'range':range(product.review),
        'res':res
    }
    return render(request, 'product/detail.html', context)


def cart_create(request, id):
    is_active_cart = models.Cart.objects.filter(is_active=True, user=request.user)
    
    if not is_active_cart:
        models.Cart.objects.create(
            user = request.user
        )
        try:
            product = models.Product.objects.get(id=id)
            cart = models.Cart.objects.get(is_active=True, user=request.user)
            models.CartProduct.objects.create(
                card = cart,
                product = product
            )
        except:
            pass
    else:
        cart = models.Cart.objects.get(is_active=True, user=request.user)
        item = models.Product.objects.get(id=id)
        try:
            product = models.CartProduct.objects.get(product = item, cart=cart)
            product.quantity += 1
            product.save()
        except:            
            models.CartProduct.objects.create(
                cart = cart,
                product = item
            ) 
    return redirect('main:index')


def carts(request):
    active = models.Cart.objects.filter(is_active=True, user=request.user)
    in_active = models.Cart.objects.filter(is_active=False, user=request.user)
    context = {
        'active':active,
        'in_active':in_active
    }
    return render(request, 'cart/carts.html', context)


def cart_sale(request, id):
    cart = models.Cart.objects.get(id=id, is_active=True)
    cart_products = models.CartProduct.objects.filter(cart=cart)
    for cart_product in cart_products:
        if cart_product.product.quantity >= cart_product.quantity:
            product = cart_product.product
            product.quantity -= cart_product.quantity
            product.save()

        else:
            return HttpResponse("Maxsulot etarli emas")
    cart.is_active = not cart.is_active
    cart.save()

    return redirect('main:index')

def cart_detail(request):
    try:
        cart = models.Cart.objects.get(is_active=True, user=request.user)
        items = models.CartProduct.objects.filter(cart=cart)
        
        context = {
            'cart': cart,
            'items': items
        }
    except:
        return HttpResponse("Sizga hali produclar yo`q")        
    return render(request, 'cart/cart_detail.html', context)

def cart_detail_delete(request):
    item_id = request.GET['items_id']
    item = models.CartProduct.objects.get(id=item_id)
    if item.quantity > 1:
        item.quantity -= 1  
        item.save()      
    else:
        item.delete()
    
    try:
        return redirect('main:cart_detail')
    except:
        return redirect('main:index')
        
        
def wishlist(request):
    items = models.WishList.objects.filter(user=request.user)
    return render(request, 'wishlist/index.html', {'items':items})


def add_wish(requset, id):
    user = requset.user
    product = models.Product.objects.get(id=id)
    try:
        models.WishList.objects.create(
            user=user,
            product=product
        )
    except:
        pass
    return redirect('main:wishlist')


def del_wish(requset, id):
    product = models.Product.objects.get(id=id)
    user = requset.user
    wish = models.WishList.objects.get(user=user, product=product).delete()
    return redirect('main:wishlist')

main/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .material-symbols-outlined {
      font-variation-settings:
      'FILL' 0,
      'wght' 400,
      'GRAD' 0,
      'opsz' 24
    }
</style>
{% endblock %}
{% block content %}
<div class="single contact">
    <div class="container">
        <div class="single-main">
            <div class="col-md-9 single-main-left">
                <div class="sngl-top">
                
                    <div class="col-md-5 single-top-left">	
                            <div class="flexslider">
                                <ul class="slides">
                                {% for img in images %}
                                <li data-thumb="{{img.image.url}}">
                                    <div class="thumb-image"> <img src="{{img.image.url}}" data-imagezoom="true" class="img-responsive" alt=""/> </div>
                                </li>
                                {% endfor %}
                                </ul>
                        </div>
                        <!-- FlexSlider -->
                        <script src="{% static 'js/imagezoom.js' %}"></script>
                        <script defer="" src="{% static 'js/jquery.flexslider.js' %}"></script>
                        <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen">

                        <script>
                        // Can also be used with $(document).ready()
                        $(window).load(function() {
                        $('.flexslider').flexslider({
                            animation: "slide",
                            controlNav: "thumbnails"
                        });
                        });
                        </script>
                    </div>	
                    <div class="col-md-7 single-top-right">
                        <div class="single-para simpleCart_shelfItem">
                        <h2>{{product.name}}</h2>
                            <div class="star-on">
                                <ul class="star-footer">
                                    {% for _ in range %}
                                        <li><a href="#"><i> </i></a></li>
                                    {% endfor %}
                                    </ul>
                            <div class="clearfix"> </div>
                            </div>
                            
                            <h5 class="item_price"> {% if product.currency == 1 %} $ {{product.price}} {% else %} {{product.price}} so`m {% endif %}</h5>
                            <p>{{product.description}}</p>
                                <a href="{% url 'main:cart_create' product.id %}" class="add-cart item_add">ADD TO CART</a>
                            
                        </div>
                    </div>
                </div>
            </div>
            {% if res %}
            <div>
                <a href="{% url 'main:del_wish' product.id %}"><img class="material-symbols-outlined" src="{% static 'images/heart.png' %}" alt=""></a>
            </div>
            {% else %}
            <div>
                <a href="{% url 'main:add_wish' product.id %}"><img class="material-symbols-outlined" src="{% static 'images/heart_minus.png' %}" alt=""></a>
            </div>
            {% endif %}

            <div class="latestproducts">
                <div class="product-one">
                    {% for product in recomendation %}
                    <div class="col-md-4 product-left p-left"> 
                        <div class="product-main simpleCart_shelfItem">
                            <a href="{% url 'main:product_detail' product.id %}" class="mask"><img class="img-responsive zoom-img" src="{{product.baner_image.url}}" alt=""></a>
                            <div class="product-bottom">
                                <h3>{{product.name}}</h3>
                                <h4><a class="item_add" href="#"><i></i></a> <span class=" item_price">{% if product.currency == 1 %} $ {{product.price}} {% else %} {{product.price}} so`m {% endif %}</span></h4>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/product/list.html
{% extends 'base.html' %}
{% block content %}

	<!--product-starts-->
	<div class="product"> 
		<div class="container">
			<div class="product-top">
				<div class="product-one">
					{% for product in products %}
					<div class="col-md-3 product-left">
						<div class="product-main simpleCart_shelfItem">
							<a href="single.html" class="mask"><img class="img-responsive zoom-img" src="{{product.baner_image.url}}" alt="" /></a>
							<div class="product-bottom">
								<h3>{{product.name}}</h3>
								<h4><a class="item_add" href="#"><i></i></a> <span class=" item_price">{{product.price}}</span></h4>
							</div>
							<!-- <div class="srch">
								<span>-50%</span>
							</div> -->
						</div>
					</div>
					{% endfor %}
					<div class="clearfix"></div>
				</div>				
			</div>
		</div>
	</div>
	<!--product-end-->
{% endblock %}