Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('category_list', views.category_list),
    path('category_detail', views.category_detail),
    path('product_list', views.product_list),
    path('product_detail/<int:id>', views.product_detail),
    path('wishlist', views.wishlist),
]

dashboard/urls.py
from . import views
from django.urls import path

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # Category
    path('list_category', views.list_category, name='list_category'),
    path('create_category', views.create_category, name='create_category'),
    path('detail_category/<int:id>', views.detail_category, name='detail_category'),
    path('delete_category/<int:id>', views.delete_category, name='delete_category'),
    # Product
    path('product_create', views.product_create, name='product_create'),
    # auth
    path('sign_in', views.sign_in, name='sign_in'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('sign_out', views.sign_out, name='sign_out'),
    path('user_update', views.user_update, name='user_update'),
    # enter product
    path('product_list', views.product_list, name='product_list'),
    path('prodect_update/<int:id>', views.prodect_update, name='prodect_update'),
    path('product_detail/<int:id>', views.product_detail, name='product_detail'),
    
    path('add_card_excel/<int:id>', views.add_card_excel, name='add_card_excel'),
    path('add_all_excel', views.add_all_excel, name='add_all_excel'),
    path('excel', views.excel, name='excel'),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('carts', views.carts, name='carts'),
    path('cart_detail', views.cart_detail, name='cart_detail'),
    path('cart/detail/delete/', views.cart_detail_delete, name='cart_detail_delete'),
    path('cart_sale/<int:id>', views.cart_sale, name='cart_sale'),
    path('cart_create/<int:id>/', views.cart_create, name='cart_create'),
    
    path('wishlist', views.wishlist, name='wishlist'),
    path('add_wish/<int:id>', views.add_wish, name='add_wish'),
    path('del_wish/<int:id>', views.del_wish, name='del_wish'),
]

main/models.py
from time import timezone
from typing import Iterable
from django.db import models
from django.contrib.auth.models import User
from functools import reduce
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from unidecode import unidecode


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(Category, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    quantity = models.IntegerField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    currency = models.SmallIntegerField(
        choices=(
            (1,'Dollar'), 
            (2, 'So`m')
            )
    ) 
    discount_price = models.DecimalField(
        decimal_places=2, 
        max_digits=10, 
        blank=True, 
        null=True
        )
    baner_image = models.ImageField(upload_to='baner/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(Product, self).save(*args, **kwargs)


    @property
    def review(self):
        reviews = ProductReview.objects.filter(product_id=self.id)
        result = reduce(lambda result, x: result +x, reviews, 0)
        try:
            result = result / reviews.count()
        except ZeroDivisionError:
            result = 0
        return result
    
    @property 
    def is_discount(self):
        if self.discount_price is None:
            return 0
        return self.discount_price > 0
    
    @property 
    def is_active(self):
        return self.quantity > 0


class EnterProduct(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity_enter_notation = models.SmallIntegerField(
        choices=(
            (0,'Ayrish'), 
            (1, 'Qo`shish')
            ), null=True, blank=True
    ) 
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(EnterProduct, self).save(*args, **kwargs)


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(ProductImage, self).save(*args, **kwargs)


class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(WishList, self).save(*args, **kwargs)

def check_duplicate_wishlist(sender, instance, **kwargs):
    if WishList.objects.filter(user=instance.user, product=instance.product).exists():
        raise ValidationError("This product is already in the wishlist.")

models.signals.pre_save.connect(check_duplicate_wishlist, sender=WishList)


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    mark = models.SmallIntegerField()
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(ProductReview, self).save(*args, **kwargs)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(Cart, self).save(*args, **kwargs)

    @property
    def quantity(self):
        quantity = 0
        products = CartProduct.objects.filter(product_id = self.id)
        for i in products:
            quantity +=i.quantity
        return quantity

    @property
    def total_price(self):
        result = 0
        for i in CartProduct.objects.filter(card_id=self.id):
            result +=(i.product.price)*i.quantity
        return result


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(unidecode(self.name))
        super(CartProduct, self).save(*args, **kwargs)
    
    @property
    def total_price(self):
        if self.product.is_discount:
            result = self.product.discount_price * self.quantity
        else:
            result = self.product.price * self.quantity
        return result

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . import models
from django.db.models import Q


def index(request):
    q = request.GET.get('q')
    if q:
        products = models.Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q))
    else: 
        products = models.Product.objects.filter(quantity__gt=0)
    categorys = models.Category.objects.all()
    category_id = request.GET.get('category_id')
    if category_id:
        products.filter(category_id=category_id)
        
    wishs = models.WishList.objects.all()
    wish_ids = []
    for obj in wishs:
        product = models.Product.objects.get(id=obj.product.id)
        wish_ids.append(product.id)
    context = {
        'products':products,
        'categorys':categorys,
        'wish_ids':wish_ids
    }
    return render(request, 'index.html', context)




def product_detail(request, id):
    product = models.Product.objects.get(id=id)
    categorys = models.Category.objects.all()
    recomendation = models.Product.objects.filter(
        category_id=product.category.id).exclude(id=product.id)[:3]
    images = models.ProductImage.objects.filter(product_id=product.id)
    try:
        wish = models.WishList.objects.get(user=request.user, product=product)
        res = wish.id
    except:
        res = 0

    context = {
        'product':product,
        'categorys':categorys,
        'recomendation':recomendation,
        'images':images,
        'range':range(product.review),
        'res':res
    }
    return render(request, 'product/detail.html', context)


def cart_create(request, id):
    is_active_cart = models.Cart.objects.filter(is_active=True, user=request.user)
    
    if not is_active_cart:
        models.Cart.objects.create(
            user = request.user
        )
        try:
            product = models.Product.objects.get(id=id)
            cart = models.Cart.objects.get(is_active=True, user=request.user)
            models.CartProduct.objects.create(
                card = cart,
                product = product
            )
        except:
            pass
    else:
        cart = models.Cart.objects.get(is_active=True, user=request.user)
        item = models.Product.objects.get(id=id)
        try:
            product = models.CartProduct.objects.get(product = item, cart=cart)
            product.quantity += 1
            product.save()
        except:            
            models.CartProduct.objects.create(
                cart = cart,
                product = item
            ) 
    return redirect('main:index')


def carts(request):
    active = models.Cart.objects.filter(is_active=True, user=request.user)
    in_active = models.Cart.objects.filter(is_active=False, user=request.user)
    context = {
        'active':active,
        'in_active':in_active
    }
    return render(request, 'cart/carts.html', context)


def cart_sale(request, id):
    cart = models.Cart.objects.get(id=id, is_active=True)
    cart_products = models.CartProduct.objects.filter(cart=cart)
    for cart_product in cart_products:
        if cart_product.product.quantity >= cart_product.quantity:
            product = cart_product.product
            product.quantity -= cart_product.quantity
            product.save()

        else:
            return HttpResponse("Maxsulot etarli emas")
    cart.is_active = not cart.is_active
    cart.save()

    return redirect('main:index')

def cart_detail(request):
    try:
        cart = models.Cart.objects.get(is_active=True, user=request.user)
        items = models.CartProduct.objects.filter(cart=cart)
        
        context = {
            'cart': cart,
            'items': items
        }
    except:
        return HttpResponse("Sizga hali produclar yo`q")        
    return render(request, 'cart/cart_detail.html', context)

def cart_detail_delete(request):
    item_id = request.GET['items_id']
    item = models.CartProduct.objects.get(id=item_id)
    if item.quantity > 1:
        item.quantity -= 1  
        item.save()      
    else:
        item.delete()
    
    try:
        return redirect('main:cart_detail')
    except:
        return redirect('main:index')
        
        
def wishlist(request):
    items = models.WishList.objects.filter(user=request.user)
    return render(request, 'wishlist/index.html', {'items':items})


def add_wish(requset, id):
    user = requset.user
    product = models.Product.objects.get(id=id)
    try:
        models.WishList.objects.create(
            user=user,
            product=product
        )
    except:
        pass
    return redirect('main:wishlist')


def del_wish(requset, id):
    product = models.Product.objects.get(id=id)
    user = requset.user
    wish = models.WishList.objects.get(user=user, product=product).delete()
    return redirect('main:wishlist')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Luxury Watches | Home</title>
{% block css %}{% endblock %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--jQuery(necessary for Bootstrap's JavaScript plugins)-->
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<!--Custom-Theme-files-->
<!--theme-style-->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--start-menu-->
<script src="{% static 'js/simpleCart.min.js' %}"> </script>
<link href="{% static 'css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/memenu.js' %}"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>	
<!--dropdown-->
<script src="{% static 'js/jquery.easydropdown.js' %}"></script>			
</head>
<body> 
	<!--top-header-->
	<div class="top-header">
		<div class="container">
			<div class="top-header-main">
				<div class="">
					<a href="{% url 'dashboard:sign_in' %}" class="btn btn-secondary">Accauntga kirish</a>
					<a href="{% url 'dashboard:sign_up' %}" class="btn btn-secondary">Accaunt yaratish</a>
				</div>
				<div class="col-md-6 top-header-left">
				</div>
				<div class="col-md-6 top-header-left">
					<div class="">
						<a href="{% url 'main:wishlist' %}">Wishlist</a>
					</div>
					<div class="cart box_1">
						<a href="checkout.html">
							 <div class="total">
								<span class="simpleCart_total"></span></div>
								<img src="images/cart-1.png" alt="" />
						</a>
						<p><a href="{% url 'main:cart_detail' %}" class="simpleCart_empty">Empty Cart</a></p>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--top-header-->
	<!--start-logo-->
	<div class="logo">
		<a href="index.html"><h1>Luxury Watches</h1></a>
	</div>
	<!--start-logo-->
	<!--bottom-header-->
	<div class="header-bottom">
		<div class="container">
			<div class="header">
				<div class="col-md-9 header-left">
				<div class="top-nav">
					<ul class="memenu skyblue"><li class="active"><a href="{% url 'main:index' %}">Home</a></li>
						<li class="grid"><a href="#">Category</a>
							<div class="mepanel">
								<div class="row">
									<div class="col1 me-one">
										<ul>
											{% for category in categorys%}
											<li><a href="#">{{category.name}}</a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
						</li>
						<li class="grid"><a href="contact.html">Contact</a>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="col-md-3 header-right"> 
				<form action="{% url 'main:index' %}" method="get">
					<div class="search-bar" style="display: flex;">
						<input type="text" placeholder="Search" name="q">
						<button><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
							<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
						  </svg>
						</button>
					</div>
				</div>
				</form>
			<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--bottom-header-->
	<!--Slider-Starts-Here-->
				<script src="{% static 'js/responsiveslides.min.js' %}"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
    {% block content %}
    {% endblock %}
	<!--information-starts-->
	<div class="information">
		<div class="container">
			<div class="infor-top">
				<div class="col-md-3 infor-left">
					<h3>Follow Us</h3>
					<ul>
						<li><a href="#"><span class="fb"></span><h6>Facebook</h6></a></li>
						<li><a href="#"><span class="twit"></span><h6>Twitter</h6></a></li>
						<li><a href="#"><span class="google"></span><h6>Google+</h6></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Information</h3>
					<ul>
						<li><a href="#"><p>Specials</p></a></li>
						<li><a href="#"><p>New Products</p></a></li>
						<li><a href="#"><p>Our Stores</p></a></li>
						<li><a href="contact.html"><p>Contact Us</p></a></li>
						<li><a href="#"><p>Top Sellers</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>My Account</h3>
					<ul>
						<li><a href="account.html"><p>My Account</p></a></li>
						<li><a href="#"><p>My Credit slips</p></a></li>
						<li><a href="#"><p>My Merchandise returns</p></a></li>
						<li><a href="#"><p>My Personal info</p></a></li>
						<li><a href="#"><p>My Addresses</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Store Information</h3>
					<h4>The company name,
						<span>Lorem ipsum dolor,</span>
						Glasglow Dr 40 Fe 72.</h4>
					<h5>+955 123 4567</h5>	
					<p><a href="mailto:example@email.com">contact@example.com</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--information-end-->
	<!--footer-starts-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
				<div class="col-md-6 footer-left">
					<form>
						<input type="text" value="Enter Your Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email';}">
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="col-md-6 footer-right">					
					<p>© 2015 Luxury Watches. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--footer-end-->	
</body>
</html>

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!--product-starts-->
	<div class="product"> 
		<div class="container">
			<div class="product-top">
				<div class="product-one">
					{% for product in products %}
					<div class="col-md-3 product-left">
						<div class="product-main simpleCart_shelfItem">
							<a href="{% url 'main:product_detail' product.id %}" class="mask"><img class="img-responsive zoom-img" src="{{product.baner_image.url}}" alt="" /></a>
							<div class="product-bottom">
								<h3>{{product.name}}</h3>
								<h4><a class="item_add" href="#"><i></i></a> <span class=" item_price">{{product.price}}</span></h4>
							</div>
							{% if product.id in wish_ids %}
								<div style="margin-left: 200px; margin-top: -40px; position: absolute;">
									<a href="{% url 'main:del_wish' product.id %}"><img class="material-symbols-outlined" src="{% static 'images/heart.png' %}" alt=""></a>
								</div>								
							{% else %}
								<div style="margin-left: 200px; margin-top: -40px; position: absolute;">
									<a href="{% url 'main:add_wish' product.id %}"><img class="material-symbols-outlined" src="{% static 'images/heart_minus.png' %}" alt=""></a>
								</div>
							{% endif %}
						</div>
					</div>
					{% endfor %}
					<div class="clearfix"></div>
				</div>				
			</div>
		</div>
	</div>
	<!--product-end-->
{% endblock %}